### ISSUE TITLE
sms_jl.ipynb ISSUE with "Some Labelling Functions"  code snippet

### ISSUE THREAD

**Issue by Brshank** [decile-team/spear#17]
I have changed the directory of previously glove_w2v.txt and then ran on my local pc and installed all reqd libraries but it shows  an invalid literal for int() with base 10: 'import'

I think its an issue with gensim but can;t seem to resolve it 

i'm attaching a picture down below :

**https://cdn.discordapp.com/attachments/754057588714373325/989172192078098442/unknown.png**

**Comment by Dornavineeth** [comment]
@Brshank Please move all the downloaded data (which also inlcudes the glove_w2v.txt) to SPEAR-MAIN/data/SMS_SPAM (data/SMS_SPAM directory need to be created) directory and then try to rerun the notebook. Issue is faced because we expect the data should be in the data folder. For reference you can check [this](https://github.com/decile-team/spear/blob/dfbe1ba4e8f1d6df95ca272b0c482c42d3b59f1c/notebooks/SMS_SPAM/helper/con_scorer.py#L13)
